image: ruby:2.5.1
before_script:
  - apt-get update -qq && apt-get install
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --without staging production
stages:
  - build
  - deploy_staging

job_build:
  stage: build
  script:
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy_staging
  script:
  - gem install dpl -v 1.10.12
  - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_API_KEY
  only:
    variables:
      - $STAGING_BRANCH == $CI_COMMIT_REF_NAME

job_deploy_production:
  stage: deploy_production
  script:
  - gem install dpl -v 1.10.12
  - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_API_KEY
  only:
    variables:
      - $PRODUCTION_BRANCH == $CI_COMMIT_REF_NAME
